---
name: Generate Code from AWS documentation

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Generate code
        uses: udondan/cdk-nodejs@v0.2.0
        with:
          args: make generate

      - name: Commit and push changes
        run: |
          git diff --quiet || (
            perl -pi -e 's/^(\d+\.)(\d+)(\.\d+)$/($1).($2+1).".0"/e' VERSION &&
            git config --local user.email "action@github.com" &&
            git config --local user.name "GitHub Action" &&
            rm -rf node_modules tsconfig.json &&
            make pregenerate &&
            git add * &&
            git commit -m "Adds latest IAM updates from AWS" &&
            git push
          )
