---
name: Release

on:
  push:
    branches:
      - master
    paths:
      - VERSION

jobs:
  set-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Readme
        uses: udondan/ver2doc@v1.0.0
        with:
          FILE: README.md
          PATTERN: (iam-floyd\@|maven%20package-)[0-9.]+
          REPLACE: \${1}${VERSION}
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -m "Updates version references" -a

      - name: Push changes
        run: >
          [[ "${{ github.ref }}" == refs/tags/* ]] ||
          git push "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}

  release:
    runs-on: ubuntu-latest
    needs: set-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create tag
        run: |
          git config --local user.email "deemes79@googlemail.com"
          git config --local user.name "udondan"
          git tag -a "v$(cat VERSION)" -m 'Creates tag "v$(cat VERSION)"'
          git push "https://udondan:${{ secrets.OVERRIDE_TOKEN }}@github.com/${{ github.repository }}.git" --tags
